### ISSUE TITLE
Make it more obvious which resolution the user is in (high/low)

### ISSUE THREAD

**Issue by TimeScience** [borevitzlab/timeplayer-9000#4]
Icon changes but the button tool text doesn't update.  Maybe an onscreen text next to the current time text on the right? can we just list the resolution (I'm not sure what is more useful)

**Comment by TimeScience** [comment]
that's better, thanks.

I like the idea of listing how many images need to be loaded, but it is
confusing when the text is left at "0@lowres". Better text would be
something like

*Loaded: ###/### | Lowres/HiRes *  (or drop the "Loaded" text and just have
the ###/### text)

--
​
Tim Brown
Research Fellow, Center for Plant Energy Biology
Australian National University, Research School of Biology, Canberra ACT
0200
*bit.ly/Tim_ANU <http://bit.ly/Tim_ANU>* | tim.brown@anu.edu.au
​
+61 0419-006-102
​ (m) |
​
Skype: *TimeScience*

**Comment by gdunstone** [comment]
Im removing the entire counter because its confusing for everyone.

**Comment by gdunstone** [comment]
done.
